name: Intelligent Writing Assistance with Text Style Transfer
description: >-
  Demonstration of how the NLP task of text style transfer can be applied 
  to enhance the human writing experience.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2022-07-20"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: scripts/install_dependencies.py
    cpu: 2
    memory: 4

  - type: start_application
    short_summary: Starting streamlit application
    name: Intelligent Writing Assistance with Text Style Transfer
    subdomain: tst
    script: scripts/launch_app.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
    cpu: 2
    memory: 4
